# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 02:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new closet', max_length=40)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_type', models.CharField(default='new closet', max_length=40)),
                ('size', models.CharField(default='m', max_length=4)),
                ('season', models.CharField(default='all', max_length=20)),
                ('sex', models.CharField(default='N', max_length=1)),
                ('current_closet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_closet', to='Invetory.Closet')),
            ],
        ),
    ]
