# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invetory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAmounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tops', models.IntegerField(default=10)),
                ('bottoms', models.IntegerField(default=14)),
                ('socks', models.IntegerField(default=14)),
                ('shoes', models.IntegerField(default=3)),
                ('dress_cloths', models.IntegerField(default=4)),
                ('underwear', models.IntegerField(default=14)),
                ('swimwear', models.IntegerField(default=2)),
                ('outerwear', models.IntegerField(default=2)),
                ('onsies', models.IntegerField(default=14)),
                ('pajamas', models.IntegerField(default=10)),
                ('current_closet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Invetory.Closet')),
            ],
        ),
    ]
