# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invetory', '0002_defaultamounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='closet',
            name='age',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='closet',
            name='sex',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
