# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 23:01
from __future__ import unicode_literals

import Invetory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invetory', '0003_auto_20160308_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to=Invetory.models.image_path),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='name',
            field=models.CharField(default='no name', max_length=30),
        ),
    ]
