# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-13 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invetory', '0004_auto_20160311_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tops', models.CharField(default='M', max_length=2)),
                ('bottoms', models.CharField(default='M', max_length=2)),
                ('socks', models.CharField(default='M', max_length=2)),
                ('shoes', models.CharField(default='1', max_length=2)),
                ('dress_cloths', models.CharField(default='M', max_length=2)),
                ('underwear', models.CharField(default='M', max_length=2)),
                ('swimwear', models.CharField(default='M', max_length=2)),
                ('outerwear', models.CharField(default='M', max_length=2)),
                ('onsies', models.CharField(default='M', max_length=2)),
                ('pajamas', models.CharField(default='M', max_length=2)),
                ('current_closet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Invetory.Closet')),
            ],
        ),
    ]
