# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-20 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invetory', '0005_defaultsizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultsizes',
            name='bottoms',
            field=models.CharField(choices=[('P', 'P'), ('NB', 'NB'), ('3M', '3M'), ('6M', '6M'), ('9M', '9M'), ('12M', '12M'), ('18M', '18M'), ('24M', '24M'), ('2T', '2T'), ('3T', '3T'), ('4T', '4T'), ('5T', '5T'), ('3.5', '3.5'), ('4', '4'), ('4', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10')], default='NB', max_length=3),
        ),
        migrations.AlterField(
            model_name='defaultsizes',
            name='dress_cloths',
            field=models.CharField(choices=[('P', 'P'), ('NB', 'NB'), ('3M', '3M'), ('6M', '6M'), ('9M', '9M'), ('12M', '12M'), ('18M', '18M'), ('24M', '24M'), ('2T', '2T'), ('3T', '3T'), ('4T', '4T'), ('5T', '5T'), ('3.5', '3.5'), ('4', '4'), ('4', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10')], default='NB', max_length=3),
        ),
        migrations.AlterField(
            model_name='defaultsizes',
            name='onsies',
            field=models.CharField(choices=[('P', 'P'), ('NB', 'NB'), ('3M', '3M'), ('6M', '6M'), ('9M', '9M'), ('12M', '12M'), ('18M', '18M'), ('24M', '24M'), ('2T', '2T'), ('3T', '3T'), ('4T', '4T'), ('5T', '5T'), ('3.5', '3.5'), ('4', '4'), ('4', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10')], default='NB', max_length=3),
        ),
        migrations.AlterField(
            model_name='defaultsizes',
            name='outerwear',
            field=models.CharField(choices=[('P', 'P'), ('NB', 'NB'), ('3M', '3M'), ('6M', '6M'), ('9M', '9M'), ('12M', '12M'), ('18M', '18M'), ('24M', '24M'), ('2T', '2T'), ('3T', '3T'), ('4T', '4T'), ('5T', '5T'), ('3.5', '3.5'), ('4', '4'), ('4', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10')], default='NB', max_length=3),
        ),
        migrations.AlterField(
            model_name='defaultsizes',
            name='pajamas',
            field=models.CharField(choices=[('P', 'P'), ('NB', 'NB'), ('3M', '3M'), ('6M', '6M'), ('9M', '9M'), ('12M', '12M'), ('18M', '18M'), ('24M', '24M'), ('2T', '2T'), ('3T', '3T'), ('4T', '4T'), ('5T', '5T'), ('3.5', '3.5'), ('4', '4'), ('4', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10')], default='NB', max_length=3),
        ),
        migrations.AlterField(
            model_name='defaultsizes',
            name='shoes',
            field=models.CharField(choices=[('P', 'P'), ('NB', 'NB'), ('3M', '3M'), ('6M', '6M'), ('9M', '9M'), ('12M', '12M'), ('18M', '18M'), ('24M', '24M'), ('2T', '2T'), ('3T', '3T'), ('4T', '4T'), ('5T', '5T'), ('3.5', '3.5'), ('4', '4'), ('4', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10')], default='NB', max_length=3),
        ),
        migrations.AlterField(
            model_name='defaultsizes',
            name='socks',
            field=models.CharField(choices=[('P', 'P'), ('NB', 'NB'), ('3M', '3M'), ('6M', '6M'), ('9M', '9M'), ('12M', '12M'), ('18M', '18M'), ('24M', '24M'), ('2T', '2T'), ('3T', '3T'), ('4T', '4T'), ('5T', '5T'), ('3.5', '3.5'), ('4', '4'), ('4', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10')], default='NB', max_length=3),
        ),
        migrations.AlterField(
            model_name='defaultsizes',
            name='swimwear',
            field=models.CharField(choices=[('P', 'P'), ('NB', 'NB'), ('3M', '3M'), ('6M', '6M'), ('9M', '9M'), ('12M', '12M'), ('18M', '18M'), ('24M', '24M'), ('2T', '2T'), ('3T', '3T'), ('4T', '4T'), ('5T', '5T'), ('3.5', '3.5'), ('4', '4'), ('4', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10')], default='NB', max_length=3),
        ),
        migrations.AlterField(
            model_name='defaultsizes',
            name='tops',
            field=models.CharField(choices=[('P', 'P'), ('NB', 'NB'), ('3M', '3M'), ('6M', '6M'), ('9M', '9M'), ('12M', '12M'), ('18M', '18M'), ('24M', '24M'), ('2T', '2T'), ('3T', '3T'), ('4T', '4T'), ('5T', '5T'), ('3.5', '3.5'), ('4', '4'), ('4', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10')], default='NB', max_length=3),
        ),
        migrations.AlterField(
            model_name='defaultsizes',
            name='underwear',
            field=models.CharField(choices=[('P', 'P'), ('NB', 'NB'), ('3M', '3M'), ('6M', '6M'), ('9M', '9M'), ('12M', '12M'), ('18M', '18M'), ('24M', '24M'), ('2T', '2T'), ('3T', '3T'), ('4T', '4T'), ('5T', '5T'), ('3.5', '3.5'), ('4', '4'), ('4', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10')], default='NB', max_length=3),
        ),
    ]
