# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-20 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invetory', '0007_auto_20160320_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closet',
            name='sex',
            field=models.CharField(default='N', max_length=7),
        ),
    ]
