# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-20 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invetory', '0008_auto_20160320_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closet',
            name='age',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
